on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  cleanup-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This pull request has been marked as stale due to inactivity. It will be closed if no further activity occurs within 7 days.'
          close-pr-message: 'Closing this pull request due to continued inactivity. Feel free to reopen if necessary!'
          days-before-stale: 90
          days-before-close: 7
          exempt-pr-labels: 'keep-open,do-not-close'
          stale-pr-label: 'stale'
<<<<<<< HEAD
<<<<<<< HEAD
=======
        
>>>>>>> 53ceb123f62d7fef0dfccbc1959a15e0d0d1acc8
=======
        
>>>>>>> 53ceb123f62d7fef0dfccbc1959a15e0d0d1acc8
